### ISSUE TITLE
Default date month value set not working & after changing month and year launch picker resets to old state

### ISSUE THREAD

**Issue by ingersolm** [dewinjm/monthyear-picker#12]
1. Open Picker - Not able to set a default Month and Year value.
2. Open Picker - select a month & year -> click Ok. Return to the picker "Selected Month & year' not able to retain.
3. Open Picker - default shows one moth extra from the current month (First time).

Please kindly help, Thanks.

**Comment by dewinjm** [comment]
You should check the demo project, because the described points are working.
