### ISSUE TITLE
How to display selected month and year into dialog?

### ISSUE THREAD

**Issue by CodingRookie97** [dewinjm/monthyear-picker#4]
After I have selected month and year, how to display that selected month and year as the default value shown in the dialog?

**Comment by dewinjm** [comment]
In the [example](https://github.com/dewinjm/monthyear-picker#example) I show you how to do it.

When you select a month and year, an OnDateSetListener event is triggered which returns the month and year selected in the dialog.

These values can be used by you when you raise the instance again to send these values.

```java
// The monthSelected values are from (0-11) where 0 is January and 11 is December.
dialogFragment = MonthYearPickerDialogFragment
                .getInstance(monthSelected, yearSelected)

dialogFragment.setOnDateSetListener(new MonthYearPickerDialog.OnDateSetListener() {
  @Override
  public void onDateSet(int year, int monthOfYear) {
     monthSelected = monthOfYear // The monthOfYear values are from (0-11) where 0 is January and 11 is December.
     yearSelected = year
  }
})
```
See the [Demo](https://github.com/dewinjm/monthyear-picker/tree/master/demo) for your better understanding.

**Comment by CodingRookie97** [comment]
Dear Developer,

Thank you for your immense help! Much appreciated!

Regards,
CodingRookie97
