### ISSUE TITLE
List of Months localized

### ISSUE THREAD

**Issue by Spettacolo83** [dewinjm/monthyear-picker#6]
Hello there,
thank you for this useful library!
Is it possible to set the Locale of the Months?
Actually I need to switch the name of the months in Spanish language but the default is in English.
I need also to show the entire string of the month, for example "January" instead of "Jan"
Thank you!

**Comment by dewinjm** [comment]
Thank you for using this library!!

- I will make some changes to accept month formats (Long and Short).

- About language, for the default location of the equipment is used: ` Locale.getDefault()`. But I will include it in a customizable way.

I will notify you when I do these feature.

**Comment by Spettacolo83** [comment]
Thank you @dewinjm really appreciated!

**Comment by dewinjm** [comment]
Hi!
Use this implementation:

Update to 1.0.2 version
```JAVA 
MonthFormat monthFormat = MonthFormat.LONG; //MonthFormat.LONG or MonthFormat.SHORT
Locale customLocale = new Locale("es-ES"); //Locale for Spanish language

MonthYearPickerDialogFragment.getInstance(
    monthSelected,
    yearSelected,
    customTitle,
    customLocale,
    monthFormat)
```
I hope this helps you!

**Comment by Spettacolo83** [comment]
@dewinjm wow! So fast! Thank you very much! I really appreciate your library now even more! ;)
