### ISSUE TITLE
How to change textcolor for the Dialog- for cancel and ok buttons?

### ISSUE THREAD

**Issue by vbiswal** [dewinjm/monthyear-picker#8]
How to change textcolor for the Dialog- for cancel and ok buttons?
I tried out with set style but was unable. Please suggest a sample code to change the color. 
Thanks in advance...

**Comment by dewinjm** [comment]
Hi, thanks for using this library!!

If you need change button colors and general text, you should use your project theme and customize.

### Example:

**Create custom styles to AlertDialog Buttons**
```xml
<style name="PositiveButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
   <item name="android:textColor">#FF4081</item>
    <item name="android:background">#26FF4081</item> <!--If you need change button background color-->
</style>

<style name="NegativeButtonStyle" parent="Widget.AppCompat.Button.ButtonBar.AlertDialog">
   <item name="android:textColor">#2A2929</item>
</style>
```

**Create AlertDialog custom styles**
```xml
<style name="AlertDialogCustom" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="android:textColor">#FF4081</item> <!--Title text color-->
    <item name="android:textColorPrimary">#C92525</item> <!--Item text color-->
    <item name="android:textColorSecondary">#A11846</item> <!--If you need change separator color-->
    <item name="android:buttonBarNegativeButtonStyle">@style/NegativeButtonStyle</item>
    <item name="android:buttonBarPositiveButtonStyle">@style/PositiveButtonStyle</item>
</style>
```
**In your root theme add:**
```xml 
<item name="android:alertDialogTheme">@style/AlertDialogCustom</item>
```
**The result should be:**
<img src="https://user-images.githubusercontent.com/2231387/70650148-eb483600-1c24-11ea-909f-fdd87d8bd7e7.png" width="800" height="600" alt="example">

**Comment by vbiswal** [comment]
Thank you for your help!!! It worked...

**Comment by lambui09** [comment]
> Thank you for your help!!! It worked...

Many thanks. Please help me, change text of Button confirm Dialog.

**Comment by dewinjm** [comment]
> > Thank you for your help!!! It worked...
> 
> Many thanks. Please help me, change text of Button confirm Dialog.

Hi! Currently the values android.R.string.ok and android.R.string.cancel are used.
I will soon add custom text for the buttons.

**Comment by FernandoCCNunes** [comment]
this method does not work for me when using the app theme 'Theme.MaterialComponents.Light'

Edit:

My bad, it actually works, I was just setting a different style
