### ISSUE TITLE
Background color

### ISSUE THREAD

**Issue by sharookh0077** [dewinjm/monthyear-picker#9]
Hai, How to change background color of this datepicker?

**Comment by dewinjm** [comment]
Hi, sorry for answering late.

Add the`android:background` tag inside the `Theme.AppCompat.Light.Dialog.Alert` theme
```xml
<style name="AlertDialogCustom" parent="Theme.AppCompat.Light.Dialog.Alert">
    <item name="android:background">#FFFFFF</item>
</style>
```
This is a similar issue as #8
